# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProj' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'SDWebImage', '~> 4.0'
   pod 'IQKeyboardManager'
   pod 'SVProgressHUD'
  # Pods for SampleProj

  target 'SampleProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleProjUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
